apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - image: nginx
      name: c1
      volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
  volumes:
   - name: foo
     secret:
       secretName: secret2
