apiVersion: v1
kind: PersistentVolume
metadata:
 name: block-pv
spec:
 storageClassName: manual            #2. Standrad
 capacity: 
  storage: 1Gi
 accessModes:
  - ReadWriteOnce             #1. RWO 2. RWM 3. ROM
 hostPath:
  path: /tmp/data
